# Generated by Django 2.2.6 on 2019-12-11 06:53

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='sectionIII_general_text',
            field=wagtail.core.fields.RichTextField(default='default I'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='sectionIII_main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='sectionII_general_text',
            field=wagtail.core.fields.RichTextField(default='default II'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='sectionII_main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='sectionI_general_text',
            field=wagtail.core.fields.RichTextField(default='default III'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='sectionI_main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
