# Generated by Django 2.2.6 on 2019-11-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191112_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypage',
            old_name='meet_the_community_title_subtitle',
            new_name='meet_the_community_subtitle',
        ),
    ]
