# Generated by Django 2.2.6 on 2019-11-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191112_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypage',
            old_name='members_cards',
            new_name='member_cards',
        ),
    ]
