# Generated by Django 2.2.6 on 2019-11-12 12:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191112_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='activity_cards',
            field=wagtail.core.fields.StreamField([('activitycard', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.TextBlock(required=True)), ('l1', wagtail.core.blocks.TextBlock(required=True)), ('l2', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, null=True),
        ),
    ]
