# Generated by Django 2.2.6 on 2019-11-12 12:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20191112_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='accommodation_cards',
            field=wagtail.core.fields.StreamField([('accommodationcards', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page_link', wagtail.core.blocks.URLBlock(required=False)), ('accommodation_name', wagtail.core.blocks.TextBlock(required=True)), ('accommodation_price', wagtail.core.blocks.TextBlock(required=True)), ('attribute1_title', wagtail.core.blocks.TextBlock(required=True)), ('attribute1_text', wagtail.core.blocks.TextBlock(required=True)), ('attribute2_title', wagtail.core.blocks.TextBlock(required=True)), ('attribute2_text', wagtail.core.blocks.TextBlock(required=True)), ('attribute3_title', wagtail.core.blocks.TextBlock(required=True)), ('attribute3_text', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
