# Generated by Django 2.2.6 on 2019-12-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('community', '0009_auto_20191203_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='country_name',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='country_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
