# Generated by Django 2.2.6 on 2020-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_communitypage_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='activities_cards_sub_title',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='additional_activities_sub_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
