# Generated by Django 3.0.3 on 2020-03-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20200201_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='how_to_get_there_description',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='how_to_get_there_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
