# Generated by Django 3.0.3 on 2020-04-13 05:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20200308_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='how_to_get_there_description',
            field=wagtail.core.fields.RichTextField(default='how to get there'),
            preserve_default=False,
        ),
    ]
