# Generated by Django 2.2.6 on 2019-12-10 18:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('termsAndConditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditionpage',
            name='main_title',
            field=wagtail.core.fields.RichTextField(default='default text'),
            preserve_default=False,
        ),
    ]
