# Generated by Django 2.2.6 on 2019-12-10 18:21

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('termsAndConditions', '0003_auto_20191210_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditionpage',
            name='sectionA_general_text',
            field=wagtail.core.fields.RichTextField(default='default 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsandconditionpage',
            name='sectionA_main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
