# Generated by Django 2.2.6 on 2019-11-13 03:09

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='amenities',
            field=wagtail.core.fields.StreamField([('amenities', wagtail.core.blocks.StructBlock([('icon_class', wagtail.core.blocks.TextBlock(required=True)), ('icon_name', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='amenities_section_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='description_text',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='description_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='images',
            field=wagtail.core.fields.StreamField([('images', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='images_section_subtitle',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='images_section_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='included_services_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l1',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l10',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l11',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l12',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l2',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l3',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l4',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l5',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l6',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l7',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l8',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='l9',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll1',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll10',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll11',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll12',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll2',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll3',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll4',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll5',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll6',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll7',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll8',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='ll9',
            field=models.CharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='not_included_services_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
