# Generated by Django 2.2.6 on 2019-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('accommodation', '0003_auto_20191210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationpage',
            name='community_name',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='community_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
