# Generated by Django 2.2.6 on 2019-12-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('accommodation', '0004_auto_20191211_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationpage',
            name='country_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
