# Generated by Django 2.2.6 on 2019-12-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_accommodationpage_country_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationpage',
            name='country_page',
        ),
    ]
