# Generated by Django 2.2.6 on 2020-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_accommodationpage_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationpage',
            name='included_services_subtitle',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
