# Generated by Django 2.2.6 on 2020-02-01 22:54

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_accommodationpage_included_services_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationpage',
            name='administration_fee',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='booking_form_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='breakfast_price',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='community_fund',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='room_option_prices',
            field=wagtail.core.fields.StreamField([('RoomOptionPrices', wagtail.core.blocks.StructBlock([('price', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='room_options',
            field=wagtail.core.fields.StreamField([('RoomOptions', wagtail.core.blocks.StructBlock([('room_option', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='room_options_available',
            field=models.CharField(help_text='if NO leave this field empty', max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='accommodationpage',
            name='tour_price',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
