# Generated by Django 2.2.6 on 2020-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_auto_20200201_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationpage',
            name='check',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='accommodationpage',
            name='room_options_available',
            field=models.CharField(blank=True, help_text='if NO leave this field empty', max_length=1600, null=True),
        ),
    ]
