# Generated by Django 2.2.6 on 2020-02-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0010_auto_20200201_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationpage',
            name='check',
        ),
        migrations.AlterField(
            model_name='accommodationpage',
            name='room_options_available',
            field=models.BooleanField(default=False),
        ),
    ]
