# Generated by Django 2.2.6 on 2020-02-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0011_auto_20200201_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationpage',
            name='room_options_available',
            field=models.BooleanField(default=True),
        ),
    ]
