# Generated by Django 2.2.6 on 2020-02-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0012_auto_20200201_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationpage',
            old_name='room_options_available',
            new_name='room_types_available',
        ),
    ]
