# Generated by Django 3.0.3 on 2020-03-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0016_auto_20200303_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationpage',
            old_name='tour_content_change_warning',
            new_name='tour_price',
        ),
        migrations.RemoveField(
            model_name='accommodationpage',
            name='administration_charge',
        ),
        migrations.RemoveField(
            model_name='accommodationpage',
            name='flat_fees',
        ),
        migrations.RemoveField(
            model_name='accommodationpage',
            name='per_person_charges',
        ),
        migrations.AlterField(
            model_name='accommodationpage',
            name='administration_fee',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='accommodationpage',
            name='breakfast_price',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='accommodationpage',
            name='community_fund',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
