# Generated by Django 2.2.6 on 2019-11-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_auto_20191103_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_with_video_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_with_video_text',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
