# Generated by Django 2.2.6 on 2019-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191103_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_with_video_text',
            new_name='section_with_video_additional_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_with_video_short_text',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
