# Generated by Django 2.2.6 on 2019-11-03 17:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191103_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='section_with_video_additional_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_with_video_short_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
