# Generated by Django 2.2.6 on 2019-11-07 09:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191107_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=wagtail.core.fields.StreamField([('partners', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('button_url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
