# Generated by Django 2.2.6 on 2019-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partners_section_title',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
