# Generated by Django 2.2.6 on 2019-11-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_partners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='partners_section_title',
            new_name='additional_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_with_video_additional_text',
            new_name='main_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_with_video_image',
            new_name='video_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_with_video_short_text',
        ),
    ]
