# Generated by Django 2.2.6 on 2019-11-11 08:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0020_auto_20191111_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='additional_text',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('image_and_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('header_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('main_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('additional_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True))])), ('text_and_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('header_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('main_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('additional_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_text',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
