# Generated by Django 2.2.8 on 2019-12-03 08:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20191203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headings_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headings_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headings_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='paragraphs_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='paragraphs_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='paragraphs_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('image_and_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('header_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('main_text', wagtail.core.blocks.TextBlock(help_text='text to the right', required=True)), ('additional_text', wagtail.core.blocks.TextBlock(required=True))])), ('text_and_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('header_text', wagtail.core.blocks.TextBlock(required=True)), ('main_text', wagtail.core.blocks.TextBlock(required=True)), ('additional_text', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
