# Generated by Django 2.2.6 on 2019-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20191210_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
