# Generated by Django 2.2.6 on 2019-12-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20191213_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='social_media_icon',
        ),
    ]
