# Generated by Django 2.2.6 on 2019-12-13 03:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_homepage_social_media_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='social_media_links',
            field=wagtail.core.fields.StreamField([('SocialMedia', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.TextBlock(required=True)), ('social_media_url', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True),
        ),
    ]
