# Generated by Django 3.0.3 on 2020-04-13 05:15

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200207_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='countries',
            field=wagtail.core.fields.StreamField([('countries', wagtail.core.blocks.StructBlock([('country_name', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pop_up_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
