# Generated by Django 3.0.3 on 2020-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200413_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='organisation_email_placeholder',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='organisation_type_placeholder',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
