# Generated by Django 2.2.6 on 2019-11-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Country Page'},
        ),
    ]
