# Generated by Django 2.2.6 on 2019-11-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0002_auto_20191107_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='country_description',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='country_name',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_colored_text_word1',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_colored_text_word2',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_text_word1',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_text_word2',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
