# Generated by Django 2.2.6 on 2019-11-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20191111_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='country_description',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='image_colored_text_word1',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='image_colored_text_word2',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='image_text_word1',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='image_text_word2',
        ),
    ]
