# Generated by Django 2.2.6 on 2019-11-11 14:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0005_remove_flexpage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='location',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('price_text', wagtail.core.blocks.TextBlock(required=True)), ('community_name', wagtail.core.blocks.TextBlock(required=True)), ('community_description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='country_description',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='country_name',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_colored_text_word1',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_colored_text_word2',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_text_word1',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='image_text_word2',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
