# Generated by Django 2.2.6 on 2019-11-11 15:11

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_auto_20191111_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='images',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('price_text', wagtail.core.blocks.TextBlock(required=True)), ('community_name', wagtail.core.blocks.TextBlock(required=True)), ('community_description', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='images_section_title',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='service_info',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='service_info_title',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('price_text', wagtail.core.blocks.TextBlock(required=True)), ('community_name', wagtail.core.blocks.TextBlock(required=True)), ('community_description', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
