# Generated by Django 2.2.6 on 2019-11-11 15:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_auto_20191111_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='images',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
