# Generated by Django 2.2.6 on 2019-11-18 08:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_auto_20191111_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('page_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('price_text', wagtail.core.blocks.TextBlock(required=True)), ('community_name', wagtail.core.blocks.TextBlock(required=True)), ('community_description', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
