# Generated by Django 2.2.8 on 2019-12-03 07:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_auto_20191118_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='center_lat',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='center_lng',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='markers',
            field=wagtail.core.fields.StreamField([('marker', wagtail.core.blocks.StructBlock([('community_name', wagtail.core.blocks.TextBlock(required=True)), ('Latitude', wagtail.core.blocks.TextBlock(required=True)), ('Longitude', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
