# Generated by Django 3.0.3 on 2020-04-13 05:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0012_flexpage_social_media_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='markers',
            field=wagtail.core.fields.StreamField([('marker', wagtail.core.blocks.StructBlock([('community_name', wagtail.core.blocks.TextBlock(required=True)), ('community_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('Latitude', wagtail.core.blocks.TextBlock(required=True)), ('Longitude', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
