# Generated by Django 2.2.6 on 2019-12-11 07:03

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('privacyPolicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicypage',
            name='sectionI_general_text',
            field=wagtail.core.fields.RichTextField(default='default I'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='sectionI_main_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
