# Generated by Django 2.2.6 on 2019-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='page_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='sub_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
