# Generated by Django 2.2.6 on 2019-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_auto_20191210_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='headings_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='headings_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='headings_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='paragraphs_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='paragraphs_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='paragraphs_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
