# Generated by Django 2.2.6 on 2019-11-15 15:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'about us Page'},
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='banner_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='com_based_cards',
            field=wagtail.core.fields.StreamField([('aboutuscard', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='com_based_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='description',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='uniq_cards',
            field=wagtail.core.fields.StreamField([('aboutuscard', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='uniq_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='we_different_cards',
            field=wagtail.core.fields.StreamField([('aboutuscard', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='we_different_title',
            field=models.CharField(max_length=1600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_title',
            field=models.CharField(max_length=1600, null=True),
        ),
    ]
