# Generated by Django 2.2.6 on 2019-12-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_aboutuspage_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='headings_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='headings_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='headings_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='paragraphs_font_color',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='paragraphs_font_family',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='paragraphs_font_size',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
